version: '3.8'

services:
  dev-tools:
    container_name: dev-tools
    image: dev-tools:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./projects:/workspace
      - ~/.gitconfig:/root/.gitconfig:ro
    environment:
      - JAVA_HOME=/opt/jdk-17.0.12
      - MAVEN_HOME=/opt/maven/apache-maven-3.9.16
    tty: true
    stdin_open: true
    command: /bin/bash
